#!/bin/bash

build () {
    if [ -f "./scripts/prebuild.sh" ]; then
        echo "Running custom prebuild..."
        ./scripts/prebuild.sh
    fi
    haunt build
}

if [ $1 == "build" ]; then
    build
    exit 0
elif [ $1 == "serve" ]; then 
    haunt serve --watch
    exit 0
elif [ $# == 2 ] && [ $1 == "publish" ]; then
    build
    cp -ra ./site/. ~/doenv/$2
    exit 0
else 
    haunt $@
    exit 0
fi
